In [ ]:
# E={(−1.222,−1.297,−1.648),(−0.604,−0.208,1.436),(1.247,0.809,−0.414),(1.247,1.826,−0.846),(−0.693,0.301,1.128),(−0.869,−1.006,0.141),(0.894,−0.425,0.203)}
# Perform a principal component analysis (PCA) on the data points in E and reduce the dimensionality to 2. Give the eigenvalues.

import numpy as np
from sklearn.decomposition import PCA

# Define the data points
E = np.array([[-1.222, -1.297, -1.648], [-0.604, -0.208, 1.436], [1.247, 0.809, -0.414], [1.247, 1.826, -0.846], [-0.693, 0.301, 1.128], [-0.869, -1.006, 0.141], [0.894, -0.425, 0.203]])
# Perform PCA and reduce dimensionality to 2
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(E)
# Get the eigenvalues
eigenvalues = pca.explained_variance_
print("Reduced Data:\n", reduced_data)
print("Eigenvalues:\n", eigenvalues)

Reduced Data:
 [[-1.52905623 -1.87114957]
 [-0.77502329  1.36618562]
 [ 1.5013116  -0.24759333]
 [ 2.26593704 -0.45389836]
 [-0.44236098  1.17429303]
 [-1.33120701 -0.06544249]
 [ 0.31039887  0.09760512]]
Eigenvalues:
 [2.06520402 1.17129394]


In [2]:
# E={(−1.222,−1.297,−1.648),(−0.604,−0.208,1.436),(1.247,0.809,−0.414),(1.247,1.826,−0.846),(−0.693,0.301,1.128),(−0.869,−1.006,0.141),(0.894,−0.425,0.203)}
# Perform a principal component analysis (PCA) on the data points in E and reduce the dimensionality to 3. Give the eigenvalues.

import numpy as np
from sklearn.decomposition import PCA

# Define the data points
E = np.array([[-1.222, -1.297, -1.648], [-0.604, -0.208, 1.436], [1.247, 0.809, -0.414], [1.247, 1.826, -0.846], [-0.693, 0.301, 1.128], [-0.869, -1.006, 0.141], [0.894, -0.425, 0.203]])
# Perform PCA and reduce dimensionality to 3
pca = PCA(n_components=3)
reduced_data = pca.fit_transform(E)
# Get the eigenvalues
eigenvalues = pca.explained_variance_
print("Reduced Data:\n", reduced_data)
print("Eigenvalues:\n", eigenvalues)

Reduced Data:
 [[-1.52905623 -1.87114957 -0.22843665]
 [-0.77502329  1.36618562 -0.05524264]
 [ 1.5013116  -0.24759333  0.25621672]
 [ 2.26593704 -0.45389836 -0.51430204]
 [-0.44236098  1.17429303 -0.51825346]
 [-1.33120701 -0.06544249  0.10335941]
 [ 0.31039887  0.09760512  0.95665865]]
Eigenvalues:
 [2.06520402 1.17129394 0.26330904]
