In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [5]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[0.5661, 0.7143, 0.1321],
         [0.2920, 0.1815, 0.3338],
         [0.5989, 0.4770, 0.9296]],

        [[0.5951, 0.1596, 0.9652],
         [0.4022, 0.2621, 0.5054],
         [0.6429, 0.4207, 0.1036]],

        [[0.0441, 0.4087, 0.5682],
         [0.3193, 0.6705, 0.2794],
         [0.3901, 0.6627, 0.4677]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([0., 0., 0.])

In [9]:
ones_like_zeros[:, 0]

tensor([1., 1., 1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x[:, 0] * 5

tensor([5., 5., 5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.9728)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[1.3782, 0.6895, 0.9619, 1.8333, 1.3066],
        [2.0312, 1.0852, 1.0218, 2.2281, 1.4909],
        [1.6734, 0.9329, 0.3841, 1.3751, 1.0182],
        [1.6519, 1.4269, 0.7804, 1.8568, 1.4890],
        [0.5774, 0.2849, 0.1301, 0.4075, 0.1849]])